apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs
        image: vishwamt/node_mongodb:latest # Replace with your image
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: mongodb://root:password@mongodb:27017/yourDatabaseName
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: nodejs-app
